.section .text
.globl _start
 
_start:


    li	x12,56
    lui	x14,0x10
    sh x12, 54(x14)    # Store half-word from x12 into memory at address x14 + 54
    
    lhu	x13,54(x14)

.section .rodata
rodata_example:
    .asciz  "Hello, world!"       # Null-terminated string
 
.section .comment
    .asciz  "Generated by riscv64-unknown-elf-gcc"